language: node_js
node_js: stable

install:
  - npm install
   
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init 
  - git config user.name "qingchenmowang"
  - git config user.email "qcxitong@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://qingchen:${ROPO_TOKEN}@${GO_REF}" master:master
branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/qingchenmowang/qingchenmowang.github.io.git
   - GO_REF: e.coding.net:qcxitong/qingchen.git